[FIX] base: ir_qweb_field:image: handle svg mimetype
Steps to reproduce
==================

- Install `hr_contract_salary,web_studio,website`
- Go to Employees
- Open studio
- Click on "Model pages"
- Create a new record
- Save it
- Click on "Go to Website"

Error while render the template
ValueError: Non-image binary fields can not be converted to HTML

Cause of the issue
==================

It crashes because the svgs are not supported in the pillow library:

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#fully-supported-formats

Solution
========

Skip the image verification if the image is an svg

opw-4820322

closes odoo/odoo#221936

Signed-off-by: Hubert Van De Walle <huvw@odoo.com>